Vagrant.configure('2') do |config|
  
  config.vm.define ENV['VM_NAME1'] do |web|
    web.vm.box = 'azure'
    web.vm.hostname = 'web'
    web.vm.provision "shell", inline: "echo WEB"
    web.ssh.private_key_path = '~/.ssh/id_rsa'

    web.vm.provider :azure do |azure, override|
      # each of the below values will default to use the env vars named as below if not specified explicitly
      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
      azure.dns_name = "raci01web"
      #azure.subnet_name = "db_subnet"

      azure.vm_image_urn = 'OpenLogic:CentOS:7.2:latest'
      azure.vm_name = ENV['VM_NAME1']
      azure.vm_size = 'Standard_D1_v2'

      azure.resource_group_name = ENV['RG_NAME']
      azure.location = ENV['LOCATION']
      azure.instance_ready_timeout = 600
      # azure.vm_password = ENV['VM_PASSW']
      azure.admin_username = "raci"
    end
  end

  config.vm.define ENV['VM_NAME2'] do |db|
    db.vm.box = 'azure'
    db.vm.hostname = 'db'
    db.vm.provision "shell", inline: "echo DB"
    db.ssh.private_key_path = '~/.ssh/id_rsa'

    db.vm.provider :azure do |azure, override|
      # each of the below values will default to use the env vars named as below if not specified explicitly
      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
      azure.dns_name = "raci01db"
      #azure.subnet_name = "db_subnet"

      azure.vm_image_urn = 'OpenLogic:CentOS:7.2:latest'
      azure.vm_name = ENV['VM_NAME2']
      azure.vm_size = 'Standard_D1_v2'

      azure.resource_group_name = ENV['RG_NAME']
      azure.location = ENV['LOCATION']
      azure.instance_ready_timeout = 600
      # azure.vm_password = ENV['VM_PASSW']
      azure.admin_username = "raci"
    end
  end
end
